// Keys match dashboard input names, including strategy-specific configuration.
export const parameterHelp = {
  symbol: 'Ticker of the stock or ETF used in the backtest, such as SPY.',
  optionType: 'Call gives the right to buy shares; put gives the right to sell shares.',
  initialBalance: 'Starting cash for the backtest, in dollars.',
  startDate: 'First date of the historical period to simulate.',
  endDate: 'Last date of the historical period to simulate.',
  callCostBuffer: 'Extra buffer in call option cost calculations; 0.05 = 5%.',
  contractSize: 'Shares represented by one option contract; normally 100.',
  coveredCallRatio: 'Fraction of the stock position used for covered calls; 1.0 = 100%.',
  dipBuyPercent: 'Fraction of available cash to spend on a dip purchase; 0.4 = 40%.',
  dipTrigger: 'Price as a fraction of the recent high that triggers dip buying; 0.92 = an 8% drop.',
  vixHighThreshold: 'VIX level for high-volatility dip settings; 0.25 represents VIX 25.',
  highVixDipTrigger: 'Dip-buy price threshold during high VIX; 0.80 = 80% of the recent high (a 20% drop).',
  highVixDipBuyPercent: 'Fraction of available cash to spend on a high-VIX dip; 0.15 = 15%.',
  vixDeleverageThreshold: 'VIX level that triggers reduced leverage; 0.25 represents VIX 25.',
  vixDeleverageTargetRatio: 'Target position value divided by account equity after reducing leverage; 1.5 = 1.5:1.',
  initialPositionPercent: 'Fraction of available cash used for the first stock purchase; 0.6 = 60%.',
  marginInterestRate: 'Annual interest rate on borrowed funds; 0.06 = 6% per year.',
  maxMarginRatio: 'Maximum position value divided by account equity; 2 = 2:1 leverage.',
  maxPositionSize: 'Maximum number of stock shares held.',
  minCommission: 'Minimum commission charged per trade, in dollars.',
  minStrikeDistance: 'Minimum gap between stock price and option strike, as a fraction; 0.015 = 1.5%.',
  minTradeSize: 'Minimum trade value in dollars; smaller trades are skipped.',
  monthlyWithdrawalRate: 'Monthly cash withdrawal percentage; enter 1.0 for 1%, or 0 for no withdrawals.',
  optionCommission: 'Commission in dollars per option contract.',
  riskFreeRate: 'Annual risk-free rate used in option pricing; 0.05 = 5%.',
  stockCommission: 'Commission in dollars per stock share.',
  volatilityScalingFactor: 'Multiplier applied to VIX-derived volatility for option pricing.',
  STRIKE: 'Exercise price of the option contract, in dollars per share.',
  RIGHT: 'Option contract type: C = call (right to buy), P = put (right to sell).',
  EXPIRATION: 'Contract expiration date as YYYYMMDD; for example, 20260220 is February 20, 2026.',
  INC_INDEX: 'Option price multiplier for the profit-taking exit; 2.0 = twice the reference price.',
  DEC_INDEX: 'Option price fraction that triggers another purchase; 0.6 = 60% of the reference price (a 40% drop).',
  MAX_ADD_LOADS: 'Maximum number of additional averaging-down purchases after opening a position.',
  OPEN_POSITION: 'Number of option contracts bought when opening a position.',
  BAR_INTERVAL: 'Time represented by each historical price bar, such as 30 minutes or 1 day.',
  USE_IV_FILTER: 'Only open positions when implied volatility (IV) is below the entry threshold.',
  IV_ENTRY_THRESHOLD: 'Maximum IV for entry when the filter is enabled; 0.30 = 30%.',
  USE_IV_SPIKE_EXIT: 'Close positions when implied volatility (IV) rises above the exit threshold.',
  IV_EXIT_THRESHOLD: 'IV level that triggers an exit when enabled; 0.50 = 50%.',
  CONFIRMATION_DAYS: 'Days a new company must remain #1 by market capitalization before switching holdings.',
  INITIAL_POSITION_PERCENT: 'Fraction of available cash used for the first leader-stock purchase; 0.6 = 60%.',
  SLIPPAGE_PERCENT: 'Simulated execution-price slippage as a fraction; 0.001 = 0.1%.',
};
